[project]
name = "playlist-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rapidfuzz>=3.14.0",
    "unidecode>=1.4.0",
]
